version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOOGLE_APPLICATION_CREDENTIALS=./texno-finance-firebase.json
    env_file:
      - .env
    ports:
      - "8181:8181"
    volumes:
      - ./files:/files
    depends_on:
      db:
        condition: service_healthy
    command: ["java", "-Xmx2048m", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app.jar", "--server.port=8181"]

  db:
    image: postgres:13.1
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5