spring:
  data.r2dbc.repositories.enabled: true
  r2dbc:
    url: r2dbc:pool:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_PROD}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_PROD}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
#security:
#  allowed-origins:
#    - https://${CORS_DOMAIN}
task:
  poolSize: 5
  threadNamePrefix: "ThreadPoolTaskScheduler"
  checkContentTask:
    executionPeriod: 60s
  stopContentTask:
    executionPeriod: 15s
  calculateCameraLogsTask:
    executionPeriod: 60s
    startedAtFromCurrentTime: 2m
    timeCoverage: 1m
logging:
  level:
    org.springframework.data.r2dbc: WARN
    dev.astera.texnofinanceserver: INFO
    org.springframework.web.server.session.DefaultWebSessionManager: INFO
    org.springframework.web.reactive.result.method.annotation.RequestBodyMethodArgumentResolver: INFO

  pattern.console: "%clr(%5p -) %clr([%X{CorrelationId}]){magenta} %clr([%7thread]) %clr(:) %clr(%replace(%m){\"password=.*, \", \"password=xxx, \"}%n%wEx)"
