-- noinspection SqlNoDataSourceInspectionForFile
CREATE TABLE IF NOT EXISTS PARTNER (
    ID VARCHAR (50) NOT NULL PRIMARY KEY,
    NAME VARCHAR (100),
    DESCRIPTION VARCHAR (100),
    STATUS SMALLINT NOT NULL,
    LOGO VARCHAR (100),
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_PARTNER_NAME UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS SYSTEM_USER (
    ID VARCHAR (50) NOT NULL PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL,
    SURNAME VARCHAR (50),
    PHONE VARCHAR (50),
    EMAIL VARCHAR (50),
    LOGIN VARCHAR (50) NOT NULL,
    LOGO VARCHAR (50),
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_USER_LOGIN UNIQUE (LOGIN)
);

CREATE TABLE IF NOT EXISTS AUTHORITY (
    ID VARCHAR (50) NOT NULL PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL,
    DESCRIPTION VARCHAR (255) NOT NULL,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_AUTHORITY_NAME UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS USER_PARTNER (
    ID VARCHAR (100) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR (50) NOT NULL REFERENCES SYSTEM_USER (ID) ON DELETE CASCADE,
    PARTNER_ID VARCHAR (50) NOT NULL REFERENCES PARTNER (ID) ON DELETE CASCADE,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_AUTHORITY (
  ID VARCHAR (100) NOT NULL PRIMARY KEY,
  USER_ID VARCHAR (50) NOT NULL REFERENCES SYSTEM_USER (ID) ON DELETE CASCADE,
  AUTHORITY_ID VARCHAR (50) NOT NULL REFERENCES AUTHORITY (ID) ON DELETE CASCADE,
  VERSION BIGINT DEFAULT 1,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PARTNER_REPORT (
  ID VARCHAR (100) NOT NULL PRIMARY KEY,
  REPORT_ID VARCHAR (50) NOT NULL REFERENCES REPORTS (ID) ON DELETE CASCADE,
  PARTNER_ID VARCHAR (50) NOT NULL REFERENCES PARTNER (ID) ON DELETE CASCADE,
  VERSION BIGINT DEFAULT 1,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS REPORTS (
    ID VARCHAR (100) NOT NULL PRIMARY KEY,
    REPORT_DATE TIMESTAMP,
    PROFIT DOUBLE PRECISION,
    PROFIT_STORE DOUBLE PRECISION,
    OTHER_PROFIT DOUBLE PRECISION,
    CLIENTS INT,
    NEW_CLIENTS INT,
    NET_ISSUE DOUBLE PRECISION,
    COST DOUBLE PRECISION,
    INVOICE DOUBLE PRECISION,
    AUCTIONEER_EQUIPMENT DOUBLE PRECISION,
    AUCTIONEER_COAT DOUBLE PRECISION,
    CASH_IN_DEPOSIT DOUBLE PRECISION,
    NOTE VARCHAR(100),
    AUCTIONEER_GOLD DOUBLE PRECISION,
    CASH_IN_DEPOSIT_GOLD DOUBLE PRECISION,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FEE (
    ID VARCHAR (100) NOT NULL PRIMARY KEY,
    FEE DOUBLE PRECISION,
    DESCRIPTION VARCHAR,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COST (
   ID VARCHAR (100) NOT NULL PRIMARY KEY,
   COST DOUBLE PRECISION,
   STABLE_COST DOUBLE PRECISION,
   MONTH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   VERSION BIGINT DEFAULT 1,
   CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PARTNER_COST (
  ID VARCHAR (100) NOT NULL PRIMARY KEY,
  PARTNER_ID VARCHAR (50) NOT NULL REFERENCES PARTNER (ID) ON DELETE CASCADE,
  COST_ID VARCHAR (50) NOT NULL REFERENCES COST (ID) ON DELETE CASCADE,
  VERSION BIGINT DEFAULT 1,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

